"""Quick summary of the scraped data."""
import pandas as pd

df = pd.read_csv("data/mobile_phones.csv")
print("=" * 60)
print("SCRAPING RESULTS SUMMARY")
print("=" * 60)
print(f"Total Records: {len(df)}")
print(f"Unique URLs: {df['ad_url'].nunique()}")
print(f"Columns: {list(df.columns)}")
print()
print("--- Brand Distribution (Top 15) ---")
print(df["brand"].value_counts().head(15).to_string())
print()
print("--- Condition Distribution ---")
print(df["condition"].value_counts().to_string())
print()
print("--- Location Distribution (Top 10) ---")
print(df["location"].value_counts().head(10).to_string())
print()
print("--- Price Stats ---")
print(f"Min: Rs {df['price'].min():,.0f}")
print(f"Max: Rs {df['price'].max():,.0f}")
print(f"Mean: Rs {df['price'].mean():,.0f}")
print(f"Median: Rs {df['price'].median():,.0f}")
print(f"Null prices: {df['price'].isna().sum()}")
print()
print("--- Storage Distribution (Top 10) ---")
print(df["storage"].value_counts().head(10).to_string())
print("=" * 60)
